; ============================================================================
; Code Section ($002200-$0041FF)
; Generated from ROM bytes - guaranteed accurate
; ============================================================================

        org     $002200

        include "modules/68k/util/counter_decrement_flag_set.asm"
        include "modules/68k/game/race/audio_frequency_update.asm"
        include "modules/68k/game/state/randomized_timer_decrement_a.asm"
        include "modules/68k/game/state/weighted_timer_average_a.asm"
        include "modules/68k/game/state/randomized_timer_decrement_b.asm"
        include "modules/68k/game/state/weighted_timer_average_b.asm"
        include "modules/68k/game/state/randomized_timer_decrement_c.asm"
        include "modules/68k/game/race/audio_trigger_frequency_calc.asm"
        include "modules/68k/game/race/randomized_sound_param_0023c2.asm"
        include "modules/68k/game/physics/weighted_average_pos_clamp_0023dc.asm"
        include "modules/68k/game/race/randomized_sound_param_00240c.asm"
        include "modules/68k/game/physics/weighted_average_pos_clamp_002426.asm"
        include "modules/68k/game/race/randomized_sound_param_002452.asm"
        include "modules/68k/display/set_flag_8507_01.asm"
        include "modules/68k/display/set_flag_8507_80.asm"
        include "modules/68k/graphics/pixel_unpack_2pairs.asm"
        include "modules/68k/graphics/pixel_unpack_1pair.asm"
        include "modules/68k/game/data/vdp_tile_unpack_0024ca.asm"
        include "modules/68k/game/hud/conditional_tile_index_expand.asm"
        include "modules/68k/game/data/vdp_tile_unpack_0025b0.asm"
        include "modules/68k/hardware-regs/mars_regs_init_13.asm"
        include "modules/68k/game/render/gfx_32x_vdp_mode_reg_setup.asm"
        include "modules/68k/game/render/mars_adapter_state_init_framebuffer_setup.asm"
        include "modules/68k/game/render/mars_framebuffer_preparation.asm"
        include "modules/68k/vdp/vdp_fill_framebuffer.asm"
        include "modules/68k/vdp/vdp_clear_palette.asm"
        include "modules/68k/vdp/vdp_fill_line_table_flat.asm"
        include "modules/68k/vdp/vdp_fill_line_table_ramp.asm"
        include "modules/68k/game/render/gfx_32x_framebuffer_palette_fill.asm"
        include "modules/68k/vdp/vdp_fill_pattern.asm"
        include "modules/68k/vdp/palette_copy_full.asm"
        include "modules/68k/vdp/palette_copy_partial.asm"
        include "modules/68k/game/render/v_int_cram_xfer_gate.asm"
        include "modules/68k/sh2/mars_comm_write.asm"
        include "modules/68k/game/render/mars_dma_xfer_vdp_fill.asm"
        include "modules/68k/game/camera/camera_param_calc.asm"
        include "modules/68k/game/state/object_enable_fields_state_dispatch.asm"
        include "modules/68k/game/physics/object_velocity_init_cond_clear.asm"
        include "modules/68k/object/entity_set_model_type0.asm"
        include "modules/68k/game/camera/camera_param_calc_b.asm"
        include "modules/68k/game/render/object_render_disp.asm"
        include "modules/68k/game/entity/entity_visibility_check.asm"
        include "modules/68k/game/camera/camera_param_calc_c.asm"
        include "modules/68k/game/state/object_param_8a_dispatch_002dca.asm"
        include "modules/68k/game/physics/object_velocity_init_002df4.asm"
        include "modules/68k/game/physics/object_velocity_init_002e14.asm"
        include "modules/68k/game/state/object_param_8a_dispatch_002e34.asm"
        include "modules/68k/game/physics/object_velocity_init_002e5e.asm"
        include "modules/68k/game/physics/object_velocity_init_002e7e.asm"
        include "modules/68k/game/render/load_disp_list_pointer_002e9e.asm"
        include "modules/68k/game/render/load_disp_list_pointer_002eb2.asm"
        include "modules/68k/game/entity/object_field_clear.asm"
        include "modules/68k/game/render/object_visibility_enable.asm"
        include "modules/68k/game/camera/camera_param_calc_d.asm"
        include "modules/68k/game/render/object_pos_copy_with_render_flags.asm"
        include "modules/68k/game/camera/camera_offset_clamping.asm"
        include "modules/68k/display/camera_offset_check.asm"
        include "modules/68k/game/camera/vdp_buffer_xfer_camera_offset_apply.asm"
        include "modules/68k/game/render/vdp_config_xfer_scaled_params.asm"
        include "modules/68k/game/state/object_state_disp_0031a6.asm"
        include "modules/68k/game/race/object_timer_tick_sfx_lookup_field_clear.asm"
        include "modules/68k/game/state/load_object_pointer_clear_object_state.asm"
        include "modules/68k/game/race/race_result_recording_003272.asm"
        include "modules/68k/game/race/lap_check_disp.asm"
        include "modules/68k/game/state/set_state_0x34.asm"
        include "modules/68k/sound/sound_lookup_play.asm"
        include "modules/68k/game/race/race_result_recording_003404.asm"
        include "modules/68k/game/state/calc_state_from_flags.asm"
        include "modules/68k/game/state/object_state_disp_0034e8.asm"
        include "modules/68k/game/race/object_timer_tick_sfx_lookup.asm"
        include "modules/68k/game/state/clear_object_state_bytes.asm"
        include "modules/68k/game/race/race_result_with_leaderboard_update.asm"
        include "modules/68k/game/state/calc_state_from_flags_2.asm"
        include "modules/68k/game/render/object_table_sprite_param_update.asm"
        include "modules/68k/game/collision/object_proximity_check_jump_table_dispatch.asm"
        include "modules/68k/game/state/conditional_return_on_disp_flag.asm"
        include "modules/68k/game/collision/proximity_check_with_sine_billboard.asm"
        include "modules/68k/game/collision/sprite_init_collision_check_003924.asm"
        include "modules/68k/game/render/sprite_param_setup.asm"
        include "modules/68k/game/collision/proximity_check_simple.asm"
        include "modules/68k/game/collision/proximity_loop_iterator_a.asm"
        include "modules/68k/game/collision/sprite_init_collision_check_003a4e.asm"
        include "modules/68k/game/collision/proximity_check_062.asm"
        include "modules/68k/game/collision/object_table_3_proximity_with_animation.asm"
        include "modules/68k/game/collision/proximity_loop_iterator_b.asm"
        include "modules/68k/game/hud/sprite_hud_layout_builder.asm"
        include "modules/68k/game/render/vdp_sprite_pointer_setup_cond_disp_clear.asm"
        include "modules/68k/game/race/sfx_trigger_object_enable_fields.asm"
        include "modules/68k/game/hud/hud_element_init.asm"
        include "modules/68k/game/state/reset_timer_advance_state.asm"
        include "modules/68k/game/menu/conditional_scene_transition_003da6.asm"
        include "modules/68k/game/menu/conditional_scene_transition_003dd4.asm"
        include "modules/68k/game/render/scene_transition_check_vdp_clear.asm"
        include "modules/68k/game/scene/clear_scene_state_advance_dispatch_index.asm"
        include "modules/68k/game/scene/clear_scene_state_advance_dispatch_set_mode.asm"
        include "modules/68k/game/menu/conditional_scene_transition_003e7e.asm"
        include "modules/68k/game/menu/conditional_scene_transition_003ea2.asm"
        include "modules/68k/game/menu/conditional_scene_transition_003ec6.asm"
        include "modules/68k/game/render/scene_state_timer_vdp_output.asm"
        dc.w    $4E75        ; $003F2C
        include "modules/68k/game/render/render_slot_setup.asm"
        include "modules/68k/game/render/display_state_disp_004084.asm"
        include "modules/68k/game/physics/object_speed_ramp_up_state_advance.asm"
        include "modules/68k/game/state/check_timeout_60.asm"
        include "modules/68k/game/race/race_completion_check_lap_bit_tracking.asm"
        dc.w    $11FC        ; $0041E4
        dc.w    $0001        ; $0041E6
        dc.w    $C800        ; $0041E8
        dc.w    $11FC        ; $0041EA
        dc.w    $00F3        ; $0041EC
        dc.w    $C822        ; $0041EE
        dc.w    $0838        ; $0041F0
        dc.w    $0005        ; $0041F2
        dc.w    $C30E        ; $0041F4
        dc.w    $6604        ; $0041F6
        dc.w    $4EBA        ; $0041F8
        dc.w    $6FBE        ; $0041FA
        dc.w    $4EB9        ; $0041FC
        dc.w    $0088        ; $0041FE
