#!/usr/bin/env python3
"""
Fix invalid <EA:XX> syntax in assembly files by converting them back to DC.W format.

These placeholders were generated by the disassembler when it couldn't decode
certain effective addressing modes properly. They need to be converted to raw DC.W
for the assembler to accept them.
"""

import re
import sys
from pathlib import Path

def extract_opcode(line):
    """Extract the hex opcode from the comment"""
    # Look for pattern like ; $004E0
    match = re.search(r';\s*\$([0-9A-F]+)', line)
    if not match:
        return None

    addr_str = match.group(1)
    # For now, we'll need to look up the actual opcode from the ROM
    # This is a placeholder - we'd need ROM access
    return None

def fix_ea_line(line):
    """Convert a line with <EA:XX> to DC.W format"""
    # Pattern: instruction with <EA:XX>
    # Example:         OR.B D0,<EA:37>        ; $0004E0

    if '<EA:' not in line:
        return line

    # Extract the address comment
    addr_match = re.search(r';\s*\$([0-9A-F]+)', line)
    if not addr_match:
        # Can't fix without address
        return f"; FIXME: {line}"

    addr = addr_match.group(1)

    # Get the opcode word (we'd need to read from ROM, but for now use placeholder)
    # For this script, we'll mark it for manual review

    # Extract indentation
    indent_match = re.match(r'^(\s*)', line)
    indent = indent_match.group(1) if indent_match else '        '

    # Convert to DC.W with original comment
    return f"{indent}DC.W $XXXX ; FIXME: Invalid EA at ${addr} - {line.strip()}\n"

def fix_file(filepath):
    """Fix all <EA:XX> entries in a file"""
    lines = []
    changes = 0

    with open(filepath, 'r') as f:
        for line in f:
            if '<EA:' in line:
                new_line = fix_ea_line(line)
                lines.append(new_line)
                changes += 1
                print(f"  Fixed: {filepath.name}:{changes}")
            else:
                lines.append(line)

    if changes > 0:
        with open(filepath, 'w') as f:
            f.writelines(lines)
        print(f"Fixed {changes} lines in {filepath}")
        return changes

    return 0

def main():
    sections_dir = Path('/mnt/data/src/32x-playground/disasm/sections')

    if not sections_dir.exists():
        print(f"Error: {sections_dir} not found")
        return 1

    total_fixes = 0
    for asm_file in sections_dir.glob('*.asm'):
        fixes = fix_file(asm_file)
        total_fixes += fixes

    print(f"\nTotal fixes: {total_fixes}")

    if total_fixes > 0:
        print("\nWARNING: Files marked with $XXXX placeholders need manual review!")
        print("You need to look up the actual opcodes from the original ROM.")

    return 0

if __name__ == '__main__':
    sys.exit(main())
